version zero
poweredbyniks/taskManager pull request #1
Opened 2020-10-10 17:32 UTC by poweredbyniks

2020-10-12 17:52 UTC, zhuch-iv requested changes

2020-10-12 17:52 UTC, zhuch-iv commented on pom.xml
> +  <artifactId>TM</artifactId>
обычно маленькими буквами без сокращений

2020-10-12 17:52 UTC, zhuch-iv commented on pom.xml
> +  <groupId>org.example</groupId>
Можно получше придумать

2020-10-12 17:52 UTC, zhuch-iv commented on pom.xml
> +  <url>http://www.example.com</url>
Это можно удалить

2020-10-12 17:52 UTC, zhuch-iv commented on pom.xml
> +    <maven.compiler.source>1.7</maven.compiler.source>
Хотя бы 8 жаву

2020-10-12 17:52 UTC, zhuch-iv commented on pom.xml
> +      <version>4.11</version>
Junit 5-ый используй

2020-10-12 17:52 UTC, zhuch-iv commented on pom.xml
> +    <pluginManagement><!-- lock down plugins versions to avoid using Maven defaults (may be moved to parent pom) -->
Удаляй плагин менеджмент

2020-10-12 17:52 UTC, zhuch-iv commented on src/main/java/org/example/App.java
> + * Hello world!
Коммент лишний

2020-10-12 17:52 UTC, zhuch-iv commented on src/test/java/org/example/AppTest.java
> + * Unit test for simple App.
Напиши тесты на код желательно мерить покрытие и стремиться к 80% покрытия, мерить можно в идее

2020-10-12 17:52 UTC, zhuch-iv commented on src/main/java/org/example/Task.java
> +public class Task {
Используй `@Value` Из библиотеки ломбок

2020-10-12 17:52 UTC, zhuch-iv commented on src/main/java/org/example/Command.java
> +public interface Command {
Не понял зачем интерфейс

2020-10-12 17:52 UTC, zhuch-iv commented on src/main/java/org/example/App.java
> +        reader.close();
try-with-resources

2020-10-12 17:52 UTC, zhuch-iv commented on src/main/java/org/example/App.java
> +                if (input.equals("exit"))
Лучше в свич

2020-10-12 18:25 UTC, poweredbyniks commented on src/main/java/org/example/Command.java
> +public interface Command {
На будущее)

2020-10-14 13:33 UTC, poweredbyniks commented on src/test/java/org/example/AppTest.java
> + * Unit test for simple App.
Мб пока тесты опустим покуда у меня сейчас все в одном методе? Разнесу сперва команды на методы из свитчей и тогда тесты делать.

2020-10-14 14:53 UTC, zhuch-iv commented on src/test/java/org/example/AppTest.java
> + * Unit test for simple App.
Ну напиши хоть какие нибудь для виду

2020-10-14 14:58 UTC, zhuch-iv commented on pom.xml
> +      <dependency>
Форматирование, каждый раз когда что-то меняешь тыкай `ctrl alt L`

2020-10-14 14:58 UTC, zhuch-iv commented on pom.xml
> +    <!-- lock down plugins versions to avoid using Maven defaults (may be moved to parent pom) -->
Ты не понял эти плагины в топку, или обоснуй каждый отдельно

2020-10-14 14:58 UTC, zhuch-iv commented on src/main/java/org/example/App.java
> +                        //task
Вот таких коментов не надо пж мусор в коде

2020-10-14 14:58 UTC, zhuch-iv commented on src/main/java/org/example/Project.java
> +@Value public class Project {
Тоже форматирование не оч ставят обычно на строчке сверху

2020-10-15 14:06 UTC, poweredbyniks commented on pom.xml
> +    <!-- lock down plugins versions to avoid using Maven defaults (may be moved to parent pom) -->
теперь понял, оставил один, в комменте в pom обосновал

2020-10-28 14:35 UTC, merged