Dev
poweredbyniks/taskManager pull request #11
Opened 2021-01-07 19:54 UTC by poweredbyniks

DTO classes serialization via Jackson to JSON and vice versa.

2021-01-08 07:12 UTC, zhuch-iv requested changes

2021-01-08 07:12 UTC, zhuch-iv commented on src/main/java/org/niks/entity/Project.java
> -@Value
Нужно вернуть аннотацию

2021-01-08 07:12 UTC, zhuch-iv commented on pom.xml
> +      <artifactId>jackson-databind</artifactId>
Ещё либу с аннотациями надо добавить

2021-01-08 07:12 UTC, zhuch-iv commented on pom.xml
> +                <source>9</source>
11 лучше

2021-01-08 07:12 UTC, zhuch-iv commented on src/main/java/org/niks/Bootstrap.java
> +    public Bootstrap() throws IOException {
IO то не бросает

2021-01-08 07:12 UTC, zhuch-iv commented on src/main/java/org/niks/App.java
> +    public static void main(String[] args) throws IOException {
IO то не бросает же

2021-01-08 07:12 UTC, zhuch-iv commented on src/main/java/org/niks/repository/ISerialization.java
> +    default void writeJSON(Map<String, T> map, String filePath) throws IOException {
Вот тут лучше не интерфейс а абстрактный класс

2021-01-08 07:12 UTC, zhuch-iv commented on src/main/java/org/niks/repository/ISerialization.java
> +    T[] readJSON() throws IOException;
Методы публичные, возвращать лучше лист

2021-01-08 07:12 UTC, zhuch-iv commented on src/main/java/org/niks/repository/ProjectRepository.java
> +        Project[] projects = readJSON();
Можешь тут использовать стрим :)

2021-01-08 07:12 UTC, zhuch-iv commented on src/main/java/org/niks/repository/ProjectRepository.java
> +        return mapper.readValue(new File("/Users/elupokniks/Desktop/ProjectsData.json"), Project[].class);
Не абсолютый путь лучше путь относительный и вынести его в константу

2021-01-08 07:12 UTC, zhuch-iv commented on src/main/java/org/niks/Bootstrap.java
Можно использовать `@SneakyThrows`

2021-01-09 13:20 UTC, poweredbyniks commented on src/main/java/org/niks/entity/Project.java
> -@Value
@Value это конструктор c параметрами, equals, hashCode, геттеры и тд. Для использования джексона в DTO классах необходим конструктор по умолчанию, иначе будет:
`com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `org.niks.entity.Project` (no Creators, like default constructor, exist)`.
Т.е. нужно явным образом прописать конструктор по умолчанию, @EqualsAndHashCode, @Getter, @AllArgsConstructor. Итого получается:
`@EqualsAndHashCode
@Getter
@AllArgsConstructor
public class Project {
    private long projectID;
    private String projectName;
    private String projectDescription;
    private Date startDate;
    private Date finishDate;
    private List<Task> taskList;
    private long userID;
    private Status projectStatus;
    private Date creationDate;

    public Project() {
    }
}`

2021-01-09 13:45 UTC, zhuch-iv commented on src/main/java/org/niks/entity/Project.java
> -@Value
Нужно настроить:)

2021-01-20 15:26 UTC, zhuch-iv requested changes

2021-01-20 15:26 UTC, zhuch-iv commented on src/main/java/org/niks/entity/Project.java
> +    @Setter
`@with` вместо сеттера, поля должны быть финальными

2021-01-20 15:26 UTC, zhuch-iv commented on src/main/java/org/niks/entity/Task.java
> +@NoArgsConstructor(force = true, access = AccessLevel.PRIVATE)
Такой конструктор не нужен

2021-01-20 15:26 UTC, zhuch-iv commented on src/main/java/org/niks/entity/User.java
> +@NoArgsConstructor(force = true, access = AccessLevel.PRIVATE)
Нет смысла в конструкторе без аргументов для Value

2021-01-20 17:04 UTC, zhuch-iv approved these changes

2021-01-21 06:52 UTC, zhuch-iv requested changes

2021-01-21 06:52 UTC, zhuch-iv commented on src/main/java/org/niks/repository/ProjectRepository.java
>          return projectList;
projectMap.values().stream().collect(Collectors.toList())

2021-01-21 06:52 UTC, zhuch-iv commented on src/main/java/org/niks/repository/ProjectRepository.java
> +    public Optional<Project> findOne(@NotNull final String name) throws NoSuchElementException {
Либо `throws NoSuchElementException` либо `Optional`, я думаю лучше второй вариант

2021-01-21 06:52 UTC, zhuch-iv commented on src/main/java/org/niks/repository/ProjectRepository.java
> +        projectMap.forEach((s, project) -> {
Нельзя удалять элемент итерируясь по коллекции

2021-01-21 06:52 UTC, zhuch-iv commented on src/main/java/org/niks/repository/ProjectRepository.java
>      public void remove(@NotNull final String name) {
`projectMap.remove(name)` - ты же удаляешь по ключу тут не надо итерироваться по коллекции

2021-01-21 06:52 UTC, zhuch-iv commented on src/main/java/org/niks/repository/ProjectRepository.java
> -        for (Map.Entry<String, Project> projectEntry : projectMap.entrySet()) {
`projectMap.clear()`

2021-01-21 06:52 UTC, zhuch-iv commented on src/main/java/org/niks/repository/ProjectRepository.java
> +        projectMap.forEach((s, project) -> {
Нельзя удалять элемент во время итерирования по коллекции

2021-01-21 06:52 UTC, zhuch-iv commented on src/main/java/org/niks/repository/TaskRepository.java
> +public final class TaskRepository extends Serialization<Task> implements ITaskRepository {
Тоже самое что для `ProjectRepository`

2021-01-21 06:52 UTC, zhuch-iv commented on src/main/java/org/niks/service/ProjectService.java
> +    public Project findExactMatch(String name) throws NoSuchElementException {
`@NotNull` `final` ?

2021-01-21 06:52 UTC, zhuch-iv commented on src/main/java/org/niks/service/ProjectService.java
> +        return project;
то же самое что `projectRepository.findOne(name).get()`

2021-01-21 18:51 UTC, poweredbyniks commented on src/main/java/org/niks/repository/ProjectRepository.java
>          return projectList;
идейка предлагает заменить на конструктор new ArrayList<>(projectMap.values())

2021-01-25 19:17 UTC, zhuch-iv approved these changes

2021-01-25 19:17 UTC, zhuch-iv commented on src/main/java/org/niks/commands/ProjectListCommand.java
> +            taskService.list().forEach((task -> {
Лучше
```java
List<Task> list = taskService.list().stream()
    .filter(task.getProjectID() == project.getProjectID())
    .collect(Collectors.toList())
```

2021-01-25 19:17 UTC, zhuch-iv commented on src/main/java/org/niks/repository/ProjectRepository.java
>          return projectList;
```java
projectMap.values().stream()
    .filter(project -> project.getUserID() == currentUser().getUserID())
    .collect(Collectors.toList())
```

2021-01-25 19:17 UTC, zhuch-iv commented on src/main/java/org/niks/repository/TaskRepository.java
>          return taskList;
то же самое =)

2021-01-25 19:35 UTC, poweredbyniks commented on src/main/java/org/niks/commands/ProjectListCommand.java
> +            taskService.list().forEach((task -> {
Вот так имел ввиду?
`List<Task> list = taskService.list().stream()
                    .filter(task -> task.getProjectID() == project.getProjectID())
                    .collect(Collectors.toList());`

2021-01-25 19:37 UTC, merged