Dev
poweredbyniks/TaskManager pull request #12
Opened 2021-02-04 17:07 UTC by poweredbyniks

Refactor with spring framework.

2021-02-11 08:02 UTC, zhuch-iv requested changes

2021-02-11 08:02 UTC, zhuch-iv commented on src/main/java/org/niks/controller/TaskController.java
> +@RequestMapping("/task")
См проджект, можем созвониться по рест методам

2021-02-11 08:02 UTC, zhuch-iv commented on src/main/java/org/niks/controller/UserController.java
> +@RequestMapping("/user")
...

2021-02-11 08:02 UTC, zhuch-iv commented on src/main/java/org/niks/entity/Project.java
> +import org.springframework.stereotype.Component;
...

2021-02-11 08:02 UTC, zhuch-iv commented on src/main/java/org/niks/entity/Task.java
> +import org.springframework.stereotype.Component;
...

2021-02-11 08:02 UTC, zhuch-iv commented on src/main/java/org/niks/entity/User.java
> +import org.springframework.stereotype.Component;
...

2021-02-26 15:04 UTC, zhuch-iv requested changes

2021-02-26 15:04 UTC, zhuch-iv commented on src/main/java/org/niks/repository/ProjectRepository.java
> +                            "UPDATE projects SET projectName = ?, projectDescription = ?, " +
WERE - потерял, или ты хочешь все строчки сразу апдейтнуть, лол

2021-02-26 15:04 UTC, zhuch-iv commented on src/main/java/org/niks/repository/ProjectRepository.java
> +                    connectionPool.prepareStatement("DELETE FROM projects WHERE projectName LIKE ?");
Да блин какой `LIKE`!

2021-02-26 15:04 UTC, zhuch-iv commented on src/main/java/org/niks/repository/ProjectRepository.java
> +            String SQL = String.format("DELETE FROM projects WHERE userID = %s",
А вот в запросе с all - where

2021-03-05 07:01 UTC, poweredbyniks commented on src/main/java/org/niks/controller/UserController.java
> +    public User userVerify(@RequestBody User user) {
А логин/пароль в хеадере передавать что ли?
Или вообще опустить пока этот метод?

2021-03-05 07:49 UTC, poweredbyniks commented on src/main/java/org/niks/repository/DBConnection.java
> +    public static Connection getConnection() {
Если честн, то класс почти полностью был стырен с индусского туториала)

2021-03-09 18:44 UTC, zhuch-iv requested changes
Нужно делать pr-ы, меньше смотреть, очень много

2021-03-09 18:44 UTC, zhuch-iv commented on src/main/java/org/niks/controller/UserController.java
> +public class UserController {
Не очень, нужен пока что, юзер контроллер

2021-03-09 18:44 UTC, zhuch-iv commented on src/main/java/org/niks/controller/UserController.java
> +    public void passwordEdit(@RequestBody String newPassword) {
Не очень понятно, для какого юзера новый пароль

2021-03-09 18:44 UTC, zhuch-iv commented on src/main/java/org/niks/entity/User.java
> +import org.niks.enums.AccessRoles;
Лучше оставить старый пакет

2021-03-09 18:44 UTC, zhuch-iv commented on src/main/java/org/niks/repository/DataSourceConfiguration.java
> +        HikariConfig config = new HikariConfig("application.properties");
`application.properties` - файл для конфигов спринга, так что лучше по другому файл назвать

2021-03-09 18:44 UTC, zhuch-iv commented on src/main/java/org/niks/repository/ProjectRepository.java
> +            PreparedStatement statement
Коннекшон, стейтмент и резалт сет - нужно закрывать, можно юзать try-with-resources

2021-03-10 06:03 UTC, zhuch-iv requested changes

2021-03-10 09:27 UTC, poweredbyniks commented on src/main/java/org/niks/controller/UserController.java
> +    public void passwordEdit(@RequestBody String newPassword) {
передается в сервис новый пароль, а в сервисе он уже применяется к текущему юзеру

2021-03-10 09:27 UTC, poweredbyniks commented on src/main/java/org/niks/controller/UserController.java
> +public class UserController {
не понял коммент

2021-03-27 11:00 UTC, merged