Dev
poweredbyniks/taskManager pull request #3
Opened 2020-10-30 15:58 UTC by poweredbyniks

Выполнение задания 3 с учетом замечаний:

1. Замена UUID на рандомизированное long число
2. Замена перебора мапы "руками" на методы мапы
3. Удаление static SimpleDateFormat

Task 3 completion according to comments: 

1. long instead of UUID
2. HashMap methods instead of "hand" iteration
3. Removing static SimpleDateFormat

2020-11-02 08:08 UTC, zhuch-iv requested changes

2020-11-02 08:08 UTC, zhuch-iv commented on src/main/java/org/example/repository/TaskRepo.java
> +public class TaskRepo {
то же самое

2020-11-02 08:08 UTC, zhuch-iv commented on src/main/java/org/example/service/ProjectService.java
> +    public ProjectService(ProjectRepo projectRepo) {
че то странное - 
поле потерял

2020-11-02 08:08 UTC, zhuch-iv commented on src/main/java/org/example/service/ProjectService.java
> +    public static void projectRemove(String projectToRemove) {
`public void projectRemove(String name)`

2020-11-02 08:08 UTC, zhuch-iv commented on src/main/java/org/example/service/ProjectService.java
> +    public static void projectCreate(String projectName, String projectDescription, Date startDate, Date finishDate) {
методы не статические должны быть

2020-11-02 08:08 UTC, zhuch-iv commented on src/main/java/org/example/service/ProjectService.java
> +        return random.nextInt() + 1000;
зачем `+ 1000`?=)

2020-11-02 08:08 UTC, zhuch-iv commented on src/main/java/org/example/service/TaskService.java
> +        } else System.out.println("No such existing projects");
не делай так пж пиши полостью
```
} else {
    System.out.println("No such existing projects");
}
```

2020-11-02 08:08 UTC, zhuch-iv commented on src/main/java/org/example/service/TaskService.java
> +    public static void taskRemove(String taskToRemove) {
`public void taskRemove(String name)`

2020-11-02 08:08 UTC, zhuch-iv commented on src/main/java/org/example/service/TaskService.java
> +        if (ProjectRepo.projectMap.containsKey(projectName)) {
вместо мапы ты работаешь с методами репозитория, не статическими естественно

2020-11-02 08:31 UTC, poweredbyniks commented on src/main/java/org/example/repository/ProjectRepo.java
> +    public static Map<String, Project> projectMap = new HashMap<>();
лол, дичь была)

2020-11-02 08:32 UTC, poweredbyniks commented on src/main/java/org/example/repository/ProjectRepo.java
> +    public static Map<String, Project> projectMap = new HashMap<>();
лол, дичь была)

2020-11-04 11:34 UTC, zhuch-iv requested changes

2020-11-04 11:34 UTC, zhuch-iv commented on src/main/java/org/example/commands/HelpCommand.java
> +public class HelpCommand implements Command{
Лучше конечно перенести в другую ветку все что не относится к текущему ПР

2020-11-04 11:34 UTC, zhuch-iv commented on src/main/java/org/example/repository/ProjectRepo.java
> +    private static Map<String, Project> projectMap = new HashMap<>();
все еще статическое поле

2020-11-04 11:34 UTC, zhuch-iv commented on src/main/java/org/example/repository/ProjectRepo.java
> +        projectMap.put(project.getProjectName(), new Project(project.getProjectID(),
не понтно зачем пересоздавать объект

2020-11-04 11:34 UTC, zhuch-iv commented on src/main/java/org/example/repository/ProjectRepo.java
> +    public void update() {
`public boolean update(Project project)`

2020-11-08 11:30 UTC, poweredbyniks commented on src/main/java/org/example/repository/ProjectRepo.java
> +        projectMap.put(project.getProjectName(), new Project(project.getProjectID(),
убрал

2020-11-08 11:30 UTC, poweredbyniks commented on src/main/java/org/example/commands/HelpCommand.java
> +public class HelpCommand implements Command{
хорошо, впредь сделаю так

2020-11-08 12:13 UTC, poweredbyniks commented on src/main/java/org/example/repository/ProjectRepo.java
> +    private static Map<String, Project> projectMap = new HashMap<>();
Исправил

2020-11-08 13:55 UTC, zhuch-iv approved these changes

2020-11-08 13:55 UTC, zhuch-iv commented on src/main/java/org/example/repository/HelpRepo.java
> +public class HelpRepo {
Ну репо на Команды не нужен

2020-11-08 13:55 UTC, zhuch-iv commented on src/main/java/org/example/repository/HelpRepo.java
> +    public static Map<String, String> commandMap = new HashMap<>();
Тем более статический

2020-11-08 13:55 UTC, zhuch-iv commented on src/main/java/org/example/service/HelpService.java
> +    private HelpRepo helpRepo;
Это тоже не надо

2020-11-09 13:53 UTC, merged